### PR TITLE
test: enable state circuit test for opcodes

### PR DESCRIPTION
**Pull request by lispc**
* enable state circuit test for each opcode
* fix a state circuit bug: state circuit used RWValue::to_scalar() for word,  in fact random linear combination should be used here to be consistent with evm circuit
* add vanity check for state circuit to make debugging easier: if memory_size / global_counter exceed the circuit size limit, error msg will be reported.

### CODE REVIEW

**Comment by lispc** [comment]
this PR is most related to state circuit and test, can @ChihChengLiang and @miha-stopar have a look? Thank you!

**Review by miha-stopar — APPROVED** [review]
LGTM! Thanks!

Only two minor things, but could be ignored: perhaps add a short description in state.rs what kind of check VANITY_CHECK enables & perhaps name BytecodeTestConfig without "Bytecode", I thought it means something else (something more directly related to the byte code) when I first saw it, but it doesn't really matter.

**Comment by lispc** [comment]
totally agree with the first. For the second, I think 'TestConfig' may be too general. Is there any suggestion on its name? SimpleTxTestConfig / OpcodesTestConfig / etc? Thanks

**Comment by miha-stopar** [comment]
> totally agree with the first. For the second, I think 'TestConfig' may be too general. Is there any suggestion on its name? SimpleTxTestConfig / OpcodesTestConfig / etc? Thanks

TestConfig sounds cool to me, but don't worry, you can leave it as it is, it's totally OK. Sorry for bothering you :)

**Review by ChihChengLiang — APPROVED** [review]
LGTM. The branch needs a rebase.

**Comment by lispc** [comment]
add comments of SANITY_CHECK ( and apply the degree-fix patch to make sure CI passes)

**Pull request merged**
