### PR TITLE
docker for zkevm

### PR DESCRIPTION
**Pull request by NoCtrlZ**
I created dockerfile for zkevm circuit.
It would be necessary for integration test 😀
I would appreciate you could merge.

### CODE REVIEW

**Review by CPerezz — CHANGES_REQUESTED** [review]
LGTM modulo the following:

Should we add the installation of build-essentials no? Otherways, I think `libc` will not be linked correctly.

Also, there's one concern which is, should we build in release mode directly? Why building the lib? Shouldn't we aim to build a binary? Maybe it's a bit early to dockerize the lib only and we should wait to have a bin which orchestates the components which we can turn on via docker which would make more sense. 

Just an idea, maybe I'm missing something (might be the case probably) and if so, feel free to ignore or correct me please :smile:

**Comment by CPerezz** [comment]
Would clarify the things a lot of you say that this is a docker for benchmarking only. If so, then we replace build by bench and then makes sense to merge from my perspective. Would like to hear from @ChihChengLiang and @ed255 too if possible.

Also, if the benchmarks are the final goal of this docker PR (Doesn't seem so due to the PR comments) I would add the bench profile to the workspace `Cargo.toml`

```toml
[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = "fat"
incremental = false
codegen-units = 1
panic = "abort
```

**Comment by ed255** [comment]
> Would clarify the things a lot of you say that this is a docker for benchmarking only. If so, then we replace build by bench and then makes sense to merge from my perspective. Would like to hear from @ChihChengLiang and @ed255 too if possible.

On this note, I agree that if this Dockerfile is to be used for bechmarking, what you need to build is the benchmark binary.  Right now we only have libraries, so doing `cargo build` doesn't generate any executable.  IIRC, with criterion there's a way to build the benchmarking binary (which I think appears in `target/` under a random folder), which could then be copied to a known folder so that it can be run under the container later.  This way you only build once, and can run the benchmark many times using the container without build delays.

**Comment by NoCtrlZ** [comment]
Thank you for the review @CPerezz @ed255 
My idea is that I should do something which doesn't depend on `bus-mapping` because it was supposed to change a lot.
Now, the breaking changes PR was merged so I am going to work on bench.
I would like to integrate this PR to following PR.
https://github.com/appliedzkp/zkevm-circuits/pull/192

> Should we add the installation of build-essentials no? Otherways, I think libc will not be linked correctly.

`alpine-sdk` is that of `alpine`!

**Pull request closed without merging**
