### PR TITLE
Fix compilation error

### PR DESCRIPTION
**Pull request by ed255**
Set github actions to trigger also on push to main.

### CODE REVIEW

**Comment by HAOYUatHZ** [comment]
This can detect issue only after pushing to main. Another better option might be "Require branches to be up to date before merging" in settings -> branches -> branch protecti rule

**Review by CPerezz — APPROVED** [review]
LGTM.

I would also add the protection rule suggested by @HAOYUatHZ .

@ChihChengLiang could you add it???

**Comment by ed255** [comment]
@HAOYUatHZ @CPerezz Initially I thought that having "Require branches to be up to date before merging" was a great idea, but after discussing with @ChihChengLiang I'm worried that this change could slow down development.  Usually we have several PRs open, and this would require rebasing each one after another PR is merged; requiring more coordination effort and an extra sync between the reviewer and the PR creator before merge.  Also, this situation doesn't happen often, so we think detecting it and fixing it manually is good enough and doesn't introduce any burden.

**Comment by ChihChengLiang** [comment]
The branch protection rule might require frequent rebase from all collaborators. Say we have 3 approved PR A, B, and C, and A is merged. Then the collaborator of B would need to do 2 rebases if they don't know which of B and C get merged first.

**Review by ChihChengLiang — APPROVED** [review]
LGTM

**Comment by CPerezz** [comment]
Makes sense. 

We should probably be careful and then just add the `main` branch CI change.

Thanks for the extra thoughts on that!

**Comment by HAOYUatHZ** [comment]
> @HAOYUatHZ @CPerezz Initially I thought that having "Require branches to be up to date before merging" was a great idea, but after discussing with @ChihChengLiang I'm worried that this change could slow down development. Usually we have several PRs open, and this would require rebasing each one after another PR is merged; requiring more coordination effort and an extra sync between the reviewer and the PR creator before merge. Also, this situation doesn't happen often, so we think detecting it and fixing it manually is good enough and doesn't introduce any burden.

No problem!

**Pull request merged**
