### PR TITLE
Set rustfmt max_width to 100

### PR DESCRIPTION
**Pull request by ed255**
As discussed, we agreed to increase the `max_width` set in the rustfmt.toml to 100 in order to improve the code readability considering current standards (this is the [default used by rustfmt](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#max_width))

Apart from changing the `rustfmt.toml` I've reformatted all code to pass the CI checks using:
```sh
cargo check --all-features # required to generate `circuit-benchmarks/src/bench_params.rs`
cargo fmt --all
```

For opened PRs I'm sure that after this is merged they'll find conflicts.  Maybe the easiest way for them to resolve the conflicts will be to first update the rustfmt.toml (to set max_width = 100) and run `cargo fmt --all` in their branch, commit, and then merge main into the branch.

NOTE: I think the easiest way to verify this PR is to do the same change on a local branch and compare it with this branch and see that there are no differences.

### CODE REVIEW

**Review by CPerezz — APPROVED** [review]
LGTM. 

Just one question: Should we check whether the CI needs also to be changed to consume rustfmt.toml desired settings from the file?

As it does not make sense that the rustfmt check keeps failing.

**Comment by HAOYUatHZ** [comment]
> LGTM.
> 
> Just one question: Should we check whether the CI needs also to be changed to consume rustfmt.toml desired settings from the file?
> 
> As it does not make sense that the rustfmt check keeps failing.

looks like it's consuming it on CI (the suggestion is wider)
image

**Comment by ed255** [comment]
I think the issue was that I ran `cargo fmt --all` without doing first `cargo check --all-features`, and that resulted in my `zkevm-circuits `directory not having the file `circuit-benchmarks/src/bench_params.rs`, so the `bench_params` module in `circuit-benchmarks` was not being found by `cargo fmt` and that caused it to not complete formatting everything.

**Comment by CPerezz** [comment]
@ed255 can we merge and check the rest of PR's statuses?

**Comment by ed255** [comment]
> @ed255 can we merge and check the rest of PR's statuses?

Yes! I'll merge now

**Comment by ed255** [comment]
A note for currently open PRs:
Most likely you'll get conflicts from main because many lines have changed due to this PR (but it's just rearrangements).  Resolving the conflicts manually should be easy, but I think that if you follow this approach to update the branch it will be much less work:
1. From your PR branch edit `rustfmt.toml` and set `max_width` to `100`
2. Do `cargo check --all-features` and `cargo fmt --all`
3. `git add . && git commit -m "Reformat code with 100 chars width"`
4. `git fetch origin && git merge main`
This way, when you bring your branch up to date with main, you already have the code at 100 lines and thus reduce a lot the number of conflicts

This will affect https://github.com/appliedzkp/zkevm-circuits/pull/170 https://github.com/appliedzkp/zkevm-circuits/pull/268 https://github.com/appliedzkp/zkevm-circuits/pull/292 https://github.com/appliedzkp/zkevm-circuits/pull/297 https://github.com/appliedzkp/zkevm-circuits/pull/298 https://github.com/appliedzkp/zkevm-circuits/pull/301 https://github.com/appliedzkp/zkevm-circuits/pull/302 https://github.com/appliedzkp/zkevm-circuits/pull/303 https://github.com/appliedzkp/zkevm-circuits/pull/307 https://github.com/appliedzkp/zkevm-circuits/pull/310

**Pull request merged**
