### PR TITLE
Bench Placeholder

### PR DESCRIPTION
**Pull request by barryWhiteHat**

### CODE REVIEW

**Comment by CPerezz** [comment]
Did this timeout? @AronisAt79 

Is there any way to get deeper/more detailed logs than the ones that appear here reported to the GH actions?

**Comment by AronisAt79** [comment]
Hi @CPerezz , the prover node stores detailed log files under /home/ubuntu/CI_Prover_Benches/PR<pr number>. If the execbench script fails, prover node remains poweredup so you can login and have a look at the log.

In this case, this was the only thing written

**Comment by CPerezz** [comment]
@AronisAt79 looks like the machine ran out of RAM.. 

Is this the machine we used to benchmark everything like 1 month ago or so?

**Comment by AronisAt79** [comment]
@CPerezz , yes this is the one, currently configured with 768G of RAM.

**Comment by CPerezz** [comment]
Then I guess this should be a regression. As EVM circuit wasn't exceeding the RAM limits previously..
Ping @han0110

**Comment by han0110** [comment]
I'm also not sure, but I guess it's due to too much lookup used in `CALLDATACOPY`. Will try to find a temporary way to fix this, and also start to work on reducing the lookup for EVM circuit.

**Comment by barryWhiteHat** [comment]
@AronisAt79 is afk today but should be back tomo i think. When you get back could you bump the ram on the CI server so we don't OOM ? :)

**Comment by barryWhiteHat** [comment]
We were always expecting multi slot opcodes call , call data copy and others to grow the prover a bunch. We measured for call iirc and it did jump a bit. Lets explore a bit optimize the circuit layouter and see how that helps us.

**Comment by CPerezz** [comment]
> I'm also not sure, but I guess it's due to too much lookup used in `CALLDATACOPY`. If so, I will try to find a temporary way to fix this, and also start to work on reducing the lookup for EVM circuit.

Maybe we can not worry for now.
I mean, instead to just do a quick fix. Simply note down all of the introductions that caused the regression. 
And once the development is done, we can then go for them.

Maybe on that way you can off-load a bit and we can also advance and focus on development.

WDYT? (Of course if it takes 2TB RAM we need to do something...) I just say it in case the increase is not massive.


Also, @AronisAt79 , maybe it would be nice to display RAM and Processor which is being used. So we have the info of how much RAM was the limit etc..

**Comment by AronisAt79** [comment]
@CPerezz 

"maybe it would be nice to display RAM and Processor which is being used. So we have the info of how much RAM was the limit etc"

this will need some rewriting, currently it is only displayed if the script terminates with no error. I will for sure make the necessary adaptation. For now, we can monitor up to a few days of  system stats with netdata at  http://10.10.0.183:19999 (real time as well obviously)

btw, i will now increase the system resources. Do you want me to re trigger the bench?

**Comment by CPerezz** [comment]
Also, can we close this? Or do we want to keep this placeholder for something else?

**Pull request closed without merging**
