### PR TITLE
Replace `assert!` with `debug_assert!` and add a new profile `release-debug`

### PR DESCRIPTION
**Pull request by scroll-dev**
Close https://github.com/appliedzkp/zkevm-circuits/issues/288

### Summary

1. Only replace `assert!` with `debug_assert!` in no-test code.
2. Add a new profile `release-debug` inherited from `release` profile.

Reference comment https://github.com/appliedzkp/zkevm-circuits/issues/288#issuecomment-1015413048, we set `debug = true` for debug symbols. And `overflow-checks = true` for enabling integer overflow checks, `incremental = true` for incremental compilation.

It seems that the profile name `debug` is reserved. An error occurred when adding a custom profile named `debug` as below.

```
error: failed to parse manifest at `/zkevm-circuits/Cargo.toml`

Caused by:
  profile name `debug` is reserved
  To configure the default development profile, use the name `dev` as in [profile.dev]
  See https://doc.rust-lang.org/cargo/reference/profiles.html for more on configuring profiles.
```

### CODE REVIEW

**Review by ed255 — COMMENTED** [review]
Looks good! Nevertheless, since now we have debug_asserts, we need to make sure that we never test with release (otherwise we are testing ignoring the asserts).  So I think we need to change all the places where we are testing with release and switch to `--target release-debug`.

That would be:
- `Makefile` -> `test`
- `.github/workflows/ci.yml` -> `test`
- `integration-tests/run.sh` -> line 100

**Comment by CPerezz** [comment]
> Looks good! Nevertheless, since now we have debug_asserts, we need to make sure that we never test with release (otherwise we are testing ignoring the asserts). So I think we need to change all the places where we are testing with release and switch to `--target release-debug`.
> 
> That would be:
> 
>     * `Makefile` -> `test`
> 
>     * `.github/workflows/ci.yml` -> `test`
> 
>     * `integration-tests/run.sh` -> line 100

I think it would be better to simply overwrite the `release` profile in `Cargo.toml` and set it like:
```toml
[profile.release]
opt-level = 3
debug = false
debug-assertions = true
overflow-checks = false
rpath = false
lto = "thin"
incremental = false
```

**Comment by ed255** [comment]
> I think it would be better to simply overwrite the `release` profile in `Cargo.toml` and set it like:
> 
> ```toml
> [profile.release]
> opt-level = 3
> debug = false
> debug-assertions = true
> overflow-checks = false
> rpath = false
> lto = "thin"
> incremental = false
> ```

I think it would be very good to run our tests with `overflow-checks = true`, so if we use profile release for tests, at least I'd ask to enable that.

Notice that right now we are testing with release, which means no overflow checks, and I think that's not ideal.

**Comment by CPerezz** [comment]
SGTM. `overflow checks is not a concern.
I just added it to get faster compilations. But it's not a big deal at all.

**Review by ed255 — APPROVED** [review]

**Comment by ed255** [comment]
Thanks for applying the requested changes! Good work :)

**Pull request merged**
