### PR TITLE
chore: add Cargo.lock

### PR DESCRIPTION
**Pull request by lispc**
<https://github.com/appliedzkp/zkevm-circuits/issues/231>

### CODE REVIEW

**Comment by CPerezz** [comment]
I'm not sure I do follow the purpose of the PR.

In Rust, usually you only publish the Cargo.lock for binaries. But never for libs.
Which is the exact purpose of publishing it here?

**Comment by HAOYUatHZ** [comment]
I agree that this repo is a lib more than a bin.

But introducing Cargo.lock can avoid such an issue in https://github.com/appliedzkp/zkevm-circuits/pull/226#issuecomment-994111114 (caused by https://github.com/gakonst/ethers-rs/issues/692).

Pros vs cons though.

**Comment by CPerezz** [comment]
> I agree that this repo is a lib more than a bin.
> 
> But introducing Cargo.lock can avoid such an issue in [#226 (comment)](https://github.com/appliedzkp/zkevm-circuits/pull/226#issuecomment-994111114) (caused by [gakonst/ethers-rs#692](https://github.com/gakonst/ethers-rs/issues/692)).
> 
> Pros vs cons though.

Hmmm. The issue mentioned here would haven't been solved by adding a `Cargo.lock`. As basically the issue was on how the dependencies were stated in `ethers-providers` `Cargo.toml`.

Cargo.lock would never fix issues with that. What would do is ensure that you always work with the same dep tree. But once something gets yanked. The issue will be there no matter what Cargo.lock says.

**Comment by HAOYUatHZ** [comment]
> > I agree that this repo is a lib more than a bin.
> > But introducing Cargo.lock can avoid such an issue in [#226 (comment)](https://github.com/appliedzkp/zkevm-circuits/pull/226#issuecomment-994111114) (caused by [gakonst/ethers-rs#692](https://github.com/gakonst/ethers-rs/issues/692)).
> > Pros vs cons though.
> 
> Hmmm. The issue mentioned here would haven't been solved by adding a `Cargo.lock`. As basically the issue was on how the dependencies were stated in `ethers-providers` `Cargo.toml`.
> 
> Cargo.lock would never fix issues with that. What would do is ensure that you always work with the same dep tree. But once something gets yanked. The issue will be there no matter what Cargo.lock says.

sorry i think my word is a bit vague. i don't mean solving the dependency issue. I mean development is blocked by such an issue.
currently CI cannot work, and people cannot compile from fresh. ( if you remove ur lock file locally, you cannot compile either.)


and even if a version of a crate gets yanked, the lock file can still point to that rev and fetch it. but you are right that the dependency tree is still wrong and messy.

**Comment by HAOYUatHZ** [comment]
Another workaround can be using 
```
ethers = { git = "https://github.com/gakonst/ethers-rs" }
```
directly (and specify a tag/rev), instead of from crates.io

**Comment by CPerezz** [comment]
After some discussions we had, we will add the `Cargo.lock`. 

The purpose is anyway different. We plan to have a binary in the workspace which coordinates `bus-mapping` and circuit generation + geth.

To do so, we will need to have `Cargo.lock` uploaded.

@ed255 @ChihChengLiang can you review?

**Review by ed255 — APPROVED** [review]

**Comment by ed255** [comment]
LGTM!

**Review by ChihChengLiang — APPROVED** [review]
LGTM too

**Pull request merged**
