### PR TITLE
feat: add `sload` op (bus-mapping version)

### PR DESCRIPTION
**Pull request by HAOYUatHZ**
https://github.com/appliedzkp/zkevm-specs/pull/106

Notes:
1. would like to separate sload and sstore PR. because the gas calculation and the TxRefund calculation for `sstore` are more complicated.
2. non-bus-mapping version: https://github.com/appliedzkp/zkevm-circuits/pull/334

---

Since the bus-mapping version tests cannot really cover 1) `is_warm` 2) `reverted` cases, I just keep both "bus-mapping" and "handwrite rw_table" versions.

### CODE REVIEW

**Comment by CPerezz** [comment]
If it's not ready for review also, can we set it as WIP? And put the PR as draft?

**Comment by HAOYUatHZ** [comment]
It can be reviewed. it's just a different version of https://github.com/appliedzkp/zkevm-circuits/pull/334 and I am not sure which version is preferred.

But if we want to review it after "rebase/squash" as @ChihChengLiang suggests, I can turn it to WIP or draft.

**Comment by CPerezz** [comment]
> It can be reviewed. it's just a different version of #334 and I am not sure which version is preferred.
> 
> But if "rebase/squash" before review is preferable as @ChihChengLiang suggests, I can turn it to WIP or draft.

So we should review both and decide? What do they differ on?
For me, we can add the `non-bus-mapping` version and file an issue for the test addition once https://github.com/appliedzkp/zkevm-circuits/pull/349 is merged. 

That PR will allow to build the tests you need.

**Comment by HAOYUatHZ** [comment]
> For me, we can add the non-bus-mapping version and file an issue for the test addition once https://github.com/appliedzkp/zkevm-circuits/pull/349 is merged.

> That PR will allow to build the tests you need.

Sounds good, I will close this for now.

**Pull request closed without merging**
