### PR TITLE
Add workflow to automatically assign PR reviewers

### LINKED ISSUE #423: Implement a workflow to automatically select reviewers for PRs
Now that the reviewers group has been created @appliedzkp/zkevm-reviewers .

A workflow will trigger for each PR and select one of the members as designated reviewer for the PR.
Once that happens, the member will select  another contributor to also review the code and provide the two required approvals to merge.

### PR DESCRIPTION
**Pull request by CPerezz**
As stated in #423, it would be nice if reviews could be assigned
automatically to a group of reviwers so that the reviewing process is
more agile.

Closes #423

### CODE REVIEW

**Comment by CPerezz** [comment]
Currently affected by a bug: https://github.com/cli/cli/issues/4844

I'm not even sure this PR solved will solve the issues as the main issue is that the token does not provide this permissions directly...

**Comment by CPerezz** [comment]
Superset by #429

**Comment by HAOYUatHZ** [comment]
why not try these?

+ https://github.com/marketplace/actions/auto-request-review (I think this one fits our need best)
+ https://github.com/marketplace/actions/reviewer-lottery
+ https://github.com/cookpad/pick-random-reviewers-action

**Comment by HAOYUatHZ** [comment]
why not try these?

+ https://github.com/marketplace/actions/auto-request-review (I think this one fits our need best)
+ https://github.com/marketplace/actions/reviewer-lottery
+ https://github.com/cookpad/pick-random-reviewers-action

**Comment by HAOYUatHZ** [comment]
My point is that, seems adding @appliedzkp/zkevm-reviewers in CODEOWNERS only request 1 reviewer?  (except zkevm-circuits/src/state_circuit/ and zkevm-circuits/src/state_circuit.rs)

see https://github.com/appliedzkp/zkevm-circuits/pull/434 and https://github.com/appliedzkp/zkevm-circuits/pull/435 for an example

but https://github.com/marketplace/actions/auto-request-review allows randomly selecting `n` reviewers (`n` can be configured.)
and also allow selecting specific reviewer for specific files.

seems exactly what we need.

**Comment by HAOYUatHZ** [comment]
My point is that, seems adding @appliedzkp/zkevm-reviewers in CODEOWNERS only request 1 reviewer?  (except zkevm-circuits/src/state_circuit/ and zkevm-circuits/src/state_circuit.rs)

see https://github.com/appliedzkp/zkevm-circuits/pull/434 and https://github.com/appliedzkp/zkevm-circuits/pull/435 for an example

but https://github.com/marketplace/actions/auto-request-review allows randomly selecting `n` reviewers (`n` can be configured.)
and also allow selecting specific reviewer for specific files.

seems exactly what we need.

**Comment by CPerezz** [comment]
Hi @HAOYUatHZ 

> My point is that, seems adding @appliedzkp/zkevm-reviewers in CODEOWNERS only request 1 reviewer? 

This is done in porpuse. The group is configuref via GitHub and assigns `n` reviewers automatically. 
It was set to one now so that we could test it. 

My plan now is to add @icemelon too and if that works, add some Scroll members so that each PR gets assigned 2 reviewers. 1 from Scroll and one from appliedzkp

**Comment by HAOYUatHZ** [comment]
> Hi @HAOYUatHZ 
> 
> 
> 
> > My point is that, seems adding @appliedzkp/zkevm-reviewers in CODEOWNERS only request 1 reviewer? 
> 
> 
> 
> This is done in porpuse. The group is configuref via GitHub and assigns `n` reviewers automatically. 
> 
> It was set to one now so that we could test it. 
> 
> 
> 
> My plan now is to add @icemelon too and if that works, add some Scroll members so that each PR gets assigned 2 reviewers. 1 from Scroll and one from appliedzkp

I see.

**Pull request closed without merging**
