### PR TITLE
[WIP]Optimization Bench

### PR DESCRIPTION
**Pull request by NoCtrlZ**
# Abstract
This branch checks only `bench_evm_circuit_prover` and how the optimization improves performance.

## Performance

Degree: 19

| Step | Default | Assembly | Rebase | Assembly And Rebase | Reduction Rate |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Setup | 318.167s | 258.626s | 317.871s| 258.844s | 18.64 % |
| Prove | 5817.462s | 5745.782s | 1680.817s | 1627.667s| 72.02% |
| Verify | 114.946ms | 119.416ms | 111.262ms | 109.344ms|`4.87%` |
| Total | 6156.35s | 6022.38s |2129.42s | 1904.50s |69.06% |

| Resource | Default | Assembly | Rebase | Assembly And Rebase | Reduction Rate |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| CPU | 66.8% | 33.1% | 100.0% |100.0% |+49.70% |
| Memory | 508.6Gb | 442.8Gb | 464.9Gb| 464.1Gb|8.59% |

## Improvement
- [ ] Improve `fft`

## Done
- [x] Introduce flame graph (patch @lispc and Ho code)
- [x] Introduce pprof (patch @lispc and Ho code)
- [x] Introduce assembly
- [x] Rebase zcash halo2 latest branch (actually not latest)

## Note
I would like to get `pprof` file.

### CODE REVIEW

**Comment by barryWhiteHat** [comment]
Hmm seems like the acceleration from intel assembly seems to be so low. @AronisAt79 what CPU does the test server have ? Does virtualization block us from using cpu instruction based optimizations ?

**Comment by AronisAt79** [comment]
@barryWhiteHat i cant think of why virtualization might block optimizations. Here are the cpu details. We can repeat the specific test on other available architectures for similar instance size, if this would help.

Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          96
On-line CPU(s) list:             0-95
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
Stepping:                        7
CPU MHz:                         2499.996
BogoMIPS:                        4999.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       1.5 MiB
L1i cache:                       1.5 MiB
L2 cache:                        48 MiB
L3 cache:                        71.5 MiB
NUMA node0 CPU(s):               0-23,48-71
NUMA node1 CPU(s):               24-47,72-95

**Comment by NoCtrlZ** [comment]
No worry.
I optimized and benched it again.
It reduces about 20% time.
https://github.com/appliedzkp/pairing/pull/5#issue-1109232627

**Comment by NoCtrlZ** [comment]
The assembly doesn't affect to speed so much.
It reduces the CPU a lot.
The field arithmetic seems small parts of optimization.

**Comment by barryWhiteHat** [comment]
>  The assembly doesn't affect to speed so much.

My intuition is that that will have a bigger impact once refactor to latest zcash. Which i think will incrase CPU usages and remove other bottle knecks. 

Curious what @Brechtpd thinks about these optimistions and numbers :)

**Comment by Brechtpd** [comment]
Yeah not too surprised the prover time didn't decrease a lot with the previous halo2, would have expected it to be a little bit better than 1.23% though! :)

Current halo2 should indeed be a lot better. On my branch with optimizations I see results close to the ones shown at https://github.com/appliedzkp/pairing/pull/5#issue-1109232627 because there the bottleneck is really just raw CPU performance doing these field operations (and not doing lots of data copying and calculations in a cache unfriendly way).

**Comment by NoCtrlZ** [comment]
Thank you for the feedback!
I am going to rebase and optimize other stuff.

**Pull request closed without merging**
