### PR TITLE
opcode `ISZERO`

### PR DESCRIPTION
**Pull request by silathdiir**
spec: https://github.com/appliedzkp/zkevm-specs/pull/157

### CODE REVIEW

**Comment by ed255** [comment]
Thanks for submitting this PR!  Do you plan to add the spec for the `ISZERO` in https://github.com/appliedzkp/zkevm-specs ?

**Comment by HAOYUatHZ** [comment]
> Thanks for submitting this PR! Do you plan to add the spec for the `ISZERO` in https://github.com/appliedzkp/zkevm-specs ?

yes that's in our plan

**Review by icemelon — APPROVED** [review]
LGTM

**Review by ChihChengLiang — APPROVED** [review]
LGTM

**Pull request merged**
