### PR TITLE
enable rho check selectors

### PR DESCRIPTION
**Pull request by ChihChengLiang**
### Problem

I forgot to enable selectors in ChunkRotateConversionConfig and BlockCountAccConfig 🙈

### Solution

enable selectors and fix the test

### CODE REVIEW

**Review by CPerezz — APPROVED** [review]
LGTM!

Missed it in the review. Apologies!

**Comment by ChihChengLiang** [comment]
Sorry, it's still a work in progress. It breaks the test and emits lots of mismatched constraints that need to be fixed. 
In previous PR I was wondering why this part of constraints passed so easily. 😅

**Review by CPerezz — APPROVED** [review]
LGTM. 

Would appreciate a review from @therealyingtong as discussed with @ChihChengLiang in a call! 


Good good job mate! :heart:

**Comment by ChihChengLiang** [comment]
Thank you @CPerezz for the review ❤️ .
I'm currently unsatisfied with how I handled the BlockCount Accumulation here. I think I'm going to ship it :shipit: and fix it in a future PR.

**Pull request merged**
