### PR TITLE
Add cache to GitHub actions

### PR DESCRIPTION
**Pull request by scroll-dev**

### CODE REVIEW

**Comment by HAOYUatHZ** [comment]
for now to see the difference, we still need to manually re-run the CI on github. because it's the first time.

results on scroll repo:
__Integration Tests:__
before:
image
after:
image


__Test on ubuntu-latest:__
before:
image
after:
image

**Review by ed255 — APPROVED** [review]
LGTM!

**Review by CPerezz — APPROVED** [review]
LGTM!

**Comment by ed255** [comment]
@HAOYUatHZ Once this PR is rebased with main (and the conflicts resolved) we can merge it :)

**Comment by HAOYUatHZ** [comment]
updated! @ed255 @CPerezz

**Pull request merged**
