### PR TITLE
feat: add `sstore` circuit

### PR DESCRIPTION
**Pull request by HAOYUatHZ**

### CODE REVIEW

**Review by ed255 — COMMENTED** [review]
Overall looks good!  Thanks for working on this.

Nevertheless I see how tricky it is to calculate gas cost and refund values for this opcode.  I would be more confident reviewing this if the `SSTORE` was implemented in the bus-mapping (like I suggest in a comment).  So that the external tracer with the circuit input builder can be used, and then we can test all the different scenarios with the gas cost and refund value set by geth to test the correctness of the implementation.

Let me know your plans on implementing the `SSTORE` in the bus-mapping :)

**Comment by HAOYUatHZ** [comment]
Hi @ed255 !
1. fix stack_pointer in: https://github.com/appliedzkp/zkevm-circuits/pull/383/commits/ff397936ae3b0571fcc9811bd9dee3aee501b91c
2. update comments: https://github.com/appliedzkp/zkevm-circuits/pull/383/commits/456bd1a649d79b40d0919d748a5076ca34eedd33 (`Refund Value in units of gas` seems fine here. No need for `Refund Value in gwei`).
3. Yes, I do plan to implement the bus-mapping for `sstore`. And like https://github.com/appliedzkp/zkevm-circuits/pull/347, I believe we will need https://github.com/appliedzkp/zkevm-circuits/pull/349 gets merged first. Otherwise I cannot test `is_persist` and `is_warm` conveniently. So, should I turn this PR into draft, and then work on it after https://github.com/appliedzkp/zkevm-circuits/pull/349 being merged?

**Comment by ed255** [comment]
> 3. Yes, I do plan to implement the bus-mapping for `sstore`. And like [feat: add `sload` op (bus-mapping version) #347](https://github.com/appliedzkp/zkevm-circuits/pull/347), I believe we will need [[WIP] Modularize mock crate for easier and more customizable testing setup generation #349](https://github.com/appliedzkp/zkevm-circuits/pull/349) gets merged first. Otherwise I cannot test `is_persist` and `is_warm` conveniently. So, should I turn this PR into draft, and then work on it after [[WIP] Modularize mock crate for easier and more customizable testing setup generation #349](https://github.com/appliedzkp/zkevm-circuits/pull/349) being merged?

Thanks for pointing out that the bus-mapping implementation is blocked by #349
In that case I think it's OK to proceed without the bus-mapping implementation in order to avoid blocking this PR :)
I've opened an issue to track the bus-mapping implementation at https://github.com/appliedzkp/zkevm-circuits/issues/388

Also let's wait for a second review before merging!

**Review by ed255 — APPROVED** [review]
LGTM!

**Review by CPerezz — APPROVED** [review]
LGTM!! Nice job!!
Good catch with the stack positions too @ed255

**Comment by ed255** [comment]
@HAOYUatHZ once the PR is rebased with main and the conflicts are resolved, we can merge this :)

**Pull request merged**
